# permissions for end users to view webscrapers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: webscraper-operator
    app.kubernetes.io/managed-by: kustomize
  name: webscraper-viewer-role
rules:
- apiGroups:
  - batch.seancheng.space
  resources:
  - webscrapers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.seancheng.space
  resources:
  - webscrapers/status
  verbs:
  - get
