apiVersion: batch.seancheng.space/v1
kind: WebScraper
metadata:
  labels:
    app.kubernetes.io/name: webscraper-operator
    app.kubernetes.io/managed-by: kustomize
  name: webscraper-sample
spec:
  schedule: "*/1 * * * *" # 每分钟触发一次
  image: "busybox"
  command:
    - sh
    - -c
    - |
      if [ $((RANDOM % 2)) -eq 0 ]; then
        echo "Success";
        exit 0;
      else
        echo "Failure";
        exit 1;
      fi
  retries: 3
