apiVersion: batch.seancheng.space/v1
kind: WebScraper
metadata:
  labels:
    app.kubernetes.io/name: webscraper-operator
    app.kubernetes.io/managed-by: kustomize
  name: webscraper-sample
spec:
  schedule: "*/1 * * * *" # 每分钟触发一次 CronJob
  image: "busybox"
  command:
    - sh
    - -c
    - |
      while true; do
        if [ $((RANDOM % 2)) -eq 0 ]; then
          echo "Success";
        else
          echo "Failure";
        fi
        sleep 5;
      done
